name: Build LaTeX document
on: [push]
jobs:
    build_latex:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v3
            - name: Compile LaTeX document
              uses: xu-cheng/latex-action@v3
              with:
                  root_file: DoAn.tex
            - name: Upload PDF file
              uses: actions/upload-artifact@v3
              with:
                  name: 20183801_TranMinh_DATN
                  path: DoAn.pdf
            - name: Release
              uses: fnkr/github-action-ghr@v1.3
              if: startsWith(github.ref, 'refs/tags/')
              env:
                  GHR_PATH: DoAn.pdf
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
